# Site settings
name: Isabelle Lai
author: Isabelle Lai
title: Isabelle Lai | Software Developer
description: Everything you need to know about me
url: isa-lai.com
baseurl: ''
keywords: isa-lai,isabelle-lai,isabelle,software,developer
email: isabelle-lai@outlook.com
cover: /img/og.png
logo: /img/logo/favicon.ico
resume: 
social:
  - title: email
    url: mailto:isabelle-lai@outlook.com
  #- title: twitter
  #  url: 
  #- title: instagram
  #  url: 
  #- title: codepen
  #  url: 
  - title: github
    url: https://github.com/isa-lai
  - title: linkedin
    url: https://www.linkedin.com/in/isabelle-yuying-lai/
google_analytics:
formspree: https://formspree.io/f/xbjqpnvy
# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
